### ISSUE TITLE
Missing getTimestamp method in ExaIterator

### ISSUE THREAD

**Issue by tkilias** [exasol/udf-api-java#16]
# Background

When testing version 1.0.0 in the exaudfclient we got the following error message during build of the exaudfclient jar.

> ExaIteratorImpl.java:484: error: method does not override or implement a method from a supertype

This concerns the following method. It seems to be missing in https://github.com/exasol/udf-api-java/blob/main/src/main/java/com/exasol/ExaIterator.java#L331

>     @Override
>     public Timestamp getTimestamp(int column) throws ExaIterationException, ExaDataTypeException {

see following Github Action run https://github.com/exasol/script-languages/actions/runs/3444958299/jobs/5748126388

**Comment by redcatbear** [comment]
Closed with #17.
